workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      xcode: latest
    scripts:
      - name: Build app
        script: |
          xcodebuild build \
          -project PersonalShopperCalculator.xcodeproj \
          -scheme PersonalShopperCalculator \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/Release-iphoneos/*.app
